

//backend
const myRoute = {
    login: "/login",
    myProfile: "/profil",
    changePassword: '/user/change-mdp',
    changePasswordAtLogin: '/login/password',
    resetPassword: '/user/{userId}/reinitialise-mdp',
    changeStatusUser: '/user/{userId}/changer-status',
    roleUsersEcobank: '/fetch/create/user/banque',
    createUsersEcobank: '/create/user/banque',
    listUsersEcobank: '/liste/{page}/user/banque',
    infoUserEcobank: '/fetch/info/{userId}/user/banque',
    editionUserEcobank: '/edition/user/banque',
    addAgence: '/agence/creer',
    listAgence: '/agence/liste/{page}',
    editAgence: '/agence/edition',
    roleUsersAgence: '/fetch/create/user/agence',
    createUserAgence: '/agence/{code}/user/create',
    listUserAgence: '/agence/{code}/users/{page}',
    infoUserAgence: '/agence/{code}/users/{userId}/info',
    editUserAgence: '/agence/{code}/user/edition',
    listBorneAgence: '/borne/{codeAgence}/list/{page}',
    addBorneAgence: '/borne/{codeAgence}/ajouter',
    infoBorne: '/borne/{borneId}/info',
    editBorneAgence: '/borne/{codeAgence}/{borneId}/edition',
    removeBorne: '/borne/{borneId}/supprimer',
    listCompteAgence: '/comptes/agence/{codeAgence}/{page}/list',
    infoCompteAgence: '/compte/agence/{codeAgence}/{compteId}/info',
    addCompteAgence: '/compte/agence/{codeAgence}/ajouter',
    editCompteAgence: '/compte/agence/{codeAgence}/{compteId}/edition',
    removeCompte: '/compte/{compteId}/supprimer',
    listNewRemiseValidator: '/remise/a-valider/{page}',
    infoRemiseValidator: '/remise/{remiseId}/information',
    listMotif: '/motif/liste/{page}',
    listAllMotif: '/motif/liste',
    infoMotif: '/motif/info/{id}',
    addMotif: '/motif/ajouter',
    editMotif: '/motif/editer/{id}',
    removeMotif: '/motif/supprimer/{id}',
   
    validateCheque: '/validation/{remiseId}/remise/cheque/{chequeId}/valide',
    forceValidationCheque: '/validation/{remiseId}/remise/cheque/{chequeId}/valideforce',
    rejetCheque: '/validation/{remiseId}/remise/cheque/{chequeId}/rejet',
    cancelValidationCheque: '/validation/{remiseId}/remise/cheque/{chequeId}/annuler',
    submitValidation: '/validation/{remiseId}/remise/soumettre',
    integrateRemiseValidation: '/validation/remise/integration',
    listRemiseToBeCorrected: '/remise/a-corriger/{page}',
    infoRemiseCorrecteur: '/remise/{remiseId}/correction',
    removeCheckCorrect: '/remise/{remiseId}/cheque/{checkId}/supprimer',
    //editRemiseCorrect: '/remise/{remiseId}/rectifier',
    editCheckCorrect: '/remise/{remiseId}/cheque/{checkId}/rectifier',
    submitRemiseCorrect: '/remise/{remiseId}/submit/correction',
    listRemiseReadyIntegration: '/remise/pret-integration/{page}',
    home: '/home',
    updateSettings: '/parametre/update',
    attemptConnectionSetting: '/parametre/tentative/connection',
    sessionSettings: '/parametre/session',
    integrateurInfoRemise: '/integrateur/remise/{remiseId}/information',
    rejectCheckIntegrateur: '/validation/integrateur/{remiseId}/remise/cheque/{chequeId}/rejet',
    validateCheckIntegrateur: '/validation/integrateur/{remiseId}/remise/cheque/{chequeId}/valide',
    forceValidationCheckIntegrateur: '/validation/integrateur/{remiseId}/remise/cheque/{chequeId}/valideforce',
    cancelValidationIntegrateur: '/validation/integrateur/{remiseId}/remise/cheque/{chequeId}/annuler',
    submitValidationIntegrateur: '/validation/integrateur/{remiseId}/remise/soumettre',
    audit: '/audit/{page}',
    dataRapport: '/rapport/data',
    findRapport: '/rapport/get',
    suiviCheck: '/suivi/cheques/{page}',
    prevNextRemiseValidator: '/remise/a-valider/{id}/prevNext',
    prevNextRemiseIntegrator: '/remise/a-valider/{id}/integrateur/prevNext',
    integrationSetting: '/parametre/integration',
    integrationSettingUpdate: '/parametre/update/integration',
    escompteCheckIntegrateur: '/validation/integrateur/{checkId}/remise/escompte',
    bornePassword: '/borne/{borneId}/password',
    updateCompte: '/compte/fichier',
    nbRemiseLotGeneration: '/validation/integrateur/remise/lot/generation',
    //fournisseur
    creerFournisseur: '/fournisseur/creer',
    listeFournisseur: '/fournisseur/liste-fournisseur',
    infoFournisseur: '/fournisseur/info/{fournisseurId}',
    editionFournisseur: '/fournisseur/edition',
    supprimerFournisseur: '/fournisseur/supprimer/{id}',
    listeFournisseurAvecPagination: '/fournisseur/liste/{page}',
    fournisseurDefournisseurCentrale: '/centrale/{centraleId}/fournisseurs/associer',
    listefournisseurDefournisseurCentrale: '/centrale/fournisseurs/{idCentrale}',
    // rechercheFournisseur: '/code/{codeFournisseur}',
     rechercheFournisseur: '/code/{valeur}',
    supprimerFournisseurDeCentrale: '/centrale/fournisseurs/supprimer/{associationId}',
    importFournisseur: '/fournisseur/upload-excel',
    //user
    //article
    creerArticle: '/article/creer',
    listeArticle: '/article/liste-article',
    infoArticle: '/article/info/{articleId}',
    editionArticle: '/article/edition',
    supprimerArticle: '/article/supprimer/{id}',
    listeArticleAvecPagination: '/article/liste/{page}',
    associerFournisseursArticle: '/article/{articleId}/fournisseurs/associer',
    listeFournisseursArticle: '/article/fournisseurs/{articleId}',
    supprimerFournisseurArticle: '/article/fournisseurs/supprimer/{associationId}',
    rechercheArticle: '/article/code/{valeur}',
    listeDepartement: '/article/departements',
    listeFamille: '/article/familles',
    listeUnite: '/article/unites',

    // acheteur
    listeAcheteur: '/acheteur/liste/{page}',
    listeAllAcheteur: '/acheteur/liste',
    creerAcheteur: '/acheteur/enregistrer',
    infoAcheteur: '/acheteur/info/{acheteurId}',
    editionAcheteur: '/acheteur/edition',
    supprimerAcheteur: '/acheteur/supprimer/{id}',

     // commande
     creerCommande: '/commandes/cree',
     listeCommandeAvecPagination: '/commandes/listeCommandeAvecPagination',
    listeCommandetest: '/commandes/listeCommandes',
     infoCommande: '/commandes/detail/{id}',
     editionCommande: '/commandes/modifier/{id}',
     supprimerCommande: '/commandes/supprimer/{id}',
     listeCommande: '/commandes/listeCommande',
     rechercheCommande: '/commande/code/{codeCommande}',

     // ligne commande
     creerLigneCommande: '/commandes/lignes/{commandeId}',
     listeLigneCommande: '/commandes/{commandeId}/ligneCommande',
     infoLigneCommande: '/lignes-commandes/info/{ligneCommandeId}',
     editionLigneCommande: '/lignes-commandes/edition',
     supprimerLigneCommande: '/lignes-commandes/supprimer/{id}',
     listeLigneCommandeAvecPagination: '/lignes-commandes/liste/{page}',
     rechercheLigneCommande: '/lignes-commandes/code/{codeLigneCommande}',

     //banques

    listBanque: '/banques/liste/{page}',
    addBanque: '/banques/ajouter',
    editBanque: '/banques/editer/{id}',
    infoBanque: '/banques/info/{codeBank}',
    removeBanque: '/banques/supprimer/{id}',

     //incoterm
    listeIncoterm: '/incoterms/liste/{page}',
    addIncoterm: '/incoterms/ajouter',
    editIncoterm: '/incoterms/editer/{id}',
    removeIncoterm: '/incoterms/supprimer/{id}',

    //parametres devises
    listDevise: '/devises/liste/{page}',
    addDevise: '/devises/ajouter',
    editDevise: '/devises/editer/{id}',
    removeDevise: '/devises/supprimer/{id}',
    //parametres type fournisseur
    listTypeFournisseur: '/type-fournisseurs/liste/{page}',
    addTypeFournisseur: '/type-fournisseurs/ajouter',
    editTypeFournisseur: '/type-fournisseurs/editer/{id}',
    removeTypeFournisseur: '/type-fournisseurs/supprimer/{id}',
    
    //mode d'envoi

    listModeEnvoie: '/modes-envoie/liste/{page}',
    addModeEnvoie: '/modes-envoie/ajouter',
    editModeEnvoie: '/modes-envoie/editer/{id}',
    removeModeEnvoie: '/modes-envoie/supprimer/{id}',

    //departement

    listDepartement: '/departements/liste/{page}',
    addDepartement: '/departements/ajouter',
    editDepartement: '/departements/editer/{id}',
    removeDepartement: '/departements/supprimer/{id}',

    //echeance

    listEcheance: '/echeances/liste/{page}',
    addEcheance: '/echeances/ajouter',
    editEcheance: '/echeances/editer/{id}',
    removeEcheance: '/echeances/supprimer/{id}', 
    
};
export default myRoute;